services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - uploads_data:/app/apps/api/uploads
    # Usamos npx turbo dev para watch mode en modo desarrollo
    command: npx turbo dev --filter=api

  web-store:
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web-store/node_modules
      - /app/apps/web-store/.next
    command: npx turbo dev --filter=web-store

  admin-panel:
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/admin-panel/node_modules
    command: npx turbo dev --filter=admin-panel

volumes:
  uploads_data: 
