/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutServicesIndexRouteImport } from './routes/_layout.services.index'
import { Route as LayoutServicesCreateRouteImport } from './routes/_layout.services.create'
import { Route as LayoutServicesIdEditRouteImport } from './routes/_layout.services.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesIndexRoute = LayoutServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesCreateRoute = LayoutServicesCreateRouteImport.update({
  id: '/services/create',
  path: '/services/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesIdEditRoute = LayoutServicesIdEditRouteImport.update({
  id: '/services/$id/edit',
  path: '/services/$id/edit',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services/create': typeof LayoutServicesCreateRoute
  '/services/': typeof LayoutServicesIndexRoute
  '/services/$id/edit': typeof LayoutServicesIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof LayoutIndexRoute
  '/services/create': typeof LayoutServicesCreateRoute
  '/services': typeof LayoutServicesIndexRoute
  '/services/$id/edit': typeof LayoutServicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/services/create': typeof LayoutServicesCreateRoute
  '/_layout/services/': typeof LayoutServicesIndexRoute
  '/_layout/services/$id/edit': typeof LayoutServicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/services/create'
    | '/services/'
    | '/services/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/services/create'
    | '/services'
    | '/services/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/'
    | '/_layout/services/create'
    | '/_layout/services/'
    | '/_layout/services/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services/': {
      id: '/_layout/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof LayoutServicesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services/create': {
      id: '/_layout/services/create'
      path: '/services/create'
      fullPath: '/services/create'
      preLoaderRoute: typeof LayoutServicesCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services/$id/edit': {
      id: '/_layout/services/$id/edit'
      path: '/services/$id/edit'
      fullPath: '/services/$id/edit'
      preLoaderRoute: typeof LayoutServicesIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutServicesCreateRoute: typeof LayoutServicesCreateRoute
  LayoutServicesIndexRoute: typeof LayoutServicesIndexRoute
  LayoutServicesIdEditRoute: typeof LayoutServicesIdEditRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutServicesCreateRoute: LayoutServicesCreateRoute,
  LayoutServicesIndexRoute: LayoutServicesIndexRoute,
  LayoutServicesIdEditRoute: LayoutServicesIdEditRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
